config/routes.rb
Rails.application.routes.draw do
  root to: "homes#top"
  get "about" => "homes#about"
  devise_for :users
  resources :comments, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
    resource :favorite, only: [:create, :destroy]
    resources :favorites, only: [:index], param: :comment_id
    resources :responses, only: [:create, :destroy]
  end

  resources :users, only: [:show, :edit, :update]
  devise_scope :user do
    post 'users/guest_sign_in', to:'users/sessions#guest_sign_in', as: :guest_sign_in
  end
  get "search" => "searches#search"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/coment.rb
class Coment < ApplicationRecord
  
  has_one_attached :image
  belongs_to :user
  
end

app/models/comment.rb
class Comment < ApplicationRecord

  has_one_attached :image
  belongs_to :user
  has_many :responses, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
  
  def self.looks(search, word)
    if search == "perfect_match"
      @comment = Comment.where("body LIKE?", "#{word}")
    elsif search == "partial_match"
      @comment = Comment.where("body LIKE?", "%#{word}%")
    else
      @comment = Comment.all
    end
  end
  
  
end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :comment

  validates :user_id, uniqueness: {scope: :comment_id}

end

app/models/response.rb
class Response < ApplicationRecord

  belongs_to :user
  belongs_to :comment

  validates :response, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :comments, dependent: :destroy
  has_many :responses, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :name, presence: true, uniqueness: true

  has_one_attached :profile_image

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join("app/assets/images/no_image.jpg")
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.password_confirmation = user.password
      user.name = "ゲストユーザー"
    end
  end

  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?", "%#{word}%")
    else
      @user = User.all
    end
  end

 end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    comments_path
  end

  def after_sign_out_path_for(resource)
    about_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id
    if @comment.save
      flash[:notice] = "投稿に成功しました"
      redirect_to comments_path
    else
      flash.now[:notice] = "投稿に失敗しました"
      render :new
    end
  end

  def index
    @comments = Comment.page(params[:page])
  end

  def show
    @comment = Comment.find(params[:id])
    @response = Response.new
  end

  def destroy
    comment = Comment.find(params[:id])
    comment.destroy
    redirect_to comments_path
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])
    if @comment.update(comment_params)
      redirect_to comment_path(comment.id)
    else
      render :edit
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:title, :body)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    comment = Comment.find(params[:comment_id])
    favorite = current_user.favorites.new(comment_id: comment.id)
    favorite.save
    redirect_to comment_path(comment)
  end

  def destroy
    comment = Comment.find(params[:comment_id])
    favorite = current_user.favorites.find_by(comment_id: comment.id)
    favorite.destroy
    redirect_to comment_path(comment)
  end

  def index
    @comments = Comment.where(id: current_user.favorites.pluck(:comment_id))
    @favorites = current_user.favorites
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
before_action :authenticate_user!, except: [:top, :about]

  def top
  end

  def about
  end

end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController

  def create
    comment = Comment.find(params[:comment_id])
    response = current_user.responses.new(response_params)
    response.comment_id = comment.id
    if response.save
      flash[:notice] = "返信に成功しました"
      redirect_to comment_path(comment)
    else
      flash[:notice] = "返信に失敗しました"
      redirect_to comment_path(comment)
    end
  end

  def destroy
    Response.find(params[:id]).destroy
    redirect_to comment_path(params[:comment_id])
  end

  private

  def response_params
    params.require(:response).permit(:response)
  end

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :authenticate_user!
  
  def search
    @range = params[:range]
    
    if @range == "User"
      @users = User.looks(params[:search],params[:word])
    else
      @comments = Comment.looks(params[:search],params[:word])
    end
  end
  
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to comments_path, notice: 'ゲストユーザーとしてログインしました。'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @comments = @user.comments.page(params[:page])

  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id)
    else
      flash[:error] = "更新に失敗しました。"
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image)
  end

  def is_matching_login_user
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to comments_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coments_helper.rb
module ComentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/responses_helper.rb
module ResponsesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/coments/new.html.erb
<h1>新規投稿</h1>

<%= form_with model: @coment do |f|%>
  <h4>タイトル</h4>
  <%= f.text_field :title %>
  
  <h4>本文</h4>
  <%= f.text_area :body %>
  <%= f.submit '投稿'%>
<% end %>

app/views/comments/edit.html.erb
<div class="container-fluid">
  <div class="row no-gutters">
    <div class="col-md-3 mx-2 mx-sm-auto text-center shadow-lg rounded px-0 my-5">
      <h5 class="text-light bg-dark py-4 mb-0">編集画面</h5>
      <div class="form-group p-2">

      <div>
        <% if @comment.errors.any? %>
        <%= @comment.errors.count %>件のエラーがあります
        <ul>
          <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
        </ul>
        <% end %>
      </div>


      <%= form_with model: @comment, url: comment_path(@comment), method: :patch do |f| %>
        <div class="form-group">
          <div class="field">
            <label for="comment_title" style="float: left;">タイトル</label>
            <input class ="form-control comment-title" name="comment[title]" id="comment_title"></input>
          </div>
        </div>

        <div class="form-group">
          <div class="field">
            <label for="comment_body" style="float: left;">本文</label>
            <textarea class="form-control body" name="comment[body]" id="comment_body"></textarea>
          </div>
        </div>

        <div class="action">
          <%= f.submit '保存する', class:"btn btn-lg btn-block btn-info mt-3" %>
        </div>
      <% end %>

      </div>
    </div>
  </div>
</div>

app/views/comments/index.html.erb
<div class ="container-fluid">
  <div class="row no-gutters">
    <div class="col-md-8 mx-5 mx-sm-auto text-center shadow-lg rounded px-0 my-4">
      <h3 class ="text-light bg-dark py-3 mb-0">投稿一覧</h3>

       <div class ="col-md-10 offset-md-1">
       <table class ="table table-hover">
        <thead>
         <tr>
          <th></th>
          <th>タイトル</th>
          <th>本文</th>
         </tr>
        </thead>
        <tbody>
         <% @comments.each do |comment| %>
          <tr>
          <td>
            <%= image_tag comment.user.get_profile_image(100,100) %><br>
            <%= link_to user_path(comment.user) do %>
             <%= comment.user.name %>
            <% end %>
          </td>
          <td>
            <%= link_to comment_path(comment.id) do%>
             <%= comment.title %>
            <% end %>
          </td>
          <td>
            <%= comment.body %><br>
            <%= link_to "#{comment.responses.count}件の返信", comment_path(comment.id) %>
          </td>
          </tr>
         <% end %>

          <%= paginate @comments %>
         </div>

        </tbody>
      </table>
      </div>
    </div>
  </div>
</div>

app/views/comments/new.html.erb
<div class="container-fluid">
  <div class="row no-gutters">
    <div class="col-md-3 mx-2 mx-sm-auto text-center shadow-lg rounded px-0 my-5">
      <h3 class ="text-light bg-dark py-3 mb-0">新規投稿</h3>


      
      <div class="error-messages">
  <% if @comment.errors.any? %>
    <%= @comment.errors.count %>件のエラーがあります
    <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
</div>


   <%= form_with model: @comment do |f| %>
　   <div class ="form-new mx-3">
　     <label for="comment_title" style="float: left;">タイトル</label>
       <input class ="form-control comment-title" name="comment[title]" id="comment_title"></input>
　   </div>
　   <div class ="form-new mx-3">
　     <label for="comment_title" style="float: left;">本文</label>
　     <textarea class="form-control body" name="comment[body]" id="comment_body"></textarea>
　   </div>
　   <div class ="form-new mx-3 mb-3">
　     <%= f.submit '投稿する' ,class: "btn btn-success"%>
     </div>
   <% end %>
  </div>

  </div>
</div>

app/views/comments/show.html.erb
<div class="container-fluid">
  <div class="row no-gutters">
    <div class="col-md-8 mx-5 mx-sm-auto text-center shadow-lg rounded px-0 my-4">
      <h3 class="text-light bg-dark py-4 mb-0">投稿詳細</h3>
      <div class="form-group p-2">

        <div class="row">
          <div class = "col-md-2 mx-5 mx-sm-auto">
            <div>
              <%= image_tag @comment.user.get_profile_image(100,100) %><br>
              <p><%= @comment.user.name %></p>
              <p>タイトル：<%= @comment.title %></p>
              <p>本文：<%= @comment.body %></p>
              <p><%= @comment.created_at.strftime('%Y/%m/%d')%></p>
              <% if @comment.user == current_user %>
                <div class ="form-group">
                  <button type ="button" class ="btn btn-light border-success">
                    <%= link_to "編集する", edit_comment_path(@comment.id) %>
                  </button>
                  <button type ="button" class ="btn btn-light border-danger">
                    <%= link_to "削除する", comment_path(@comment.id), method: :delete %>
                  </button>
                </div>
              <% end %>
              <% if @comment.favorited_by?(current_user) %>
              <p>
                <%= link_to comment_favorite_path(@comment), method: :delete do %>
                  ♥<%= @comment.favorites.count %>いいね
                <% end %>
              </p>
              <% else %>
              <p>
                <%= link_to comment_favorite_path(@comment), method: :post do %>
                  ♡<%= @comment.favorites.count %>いいね
                <% end %>
              </p>
              <% end %>
              <p>返信件数:<%= @comment.responses.count %>件</p>
            </div>
            <div class ="form-group">
              <%= form_with model: [@comment, @response] do |f| %>
              <div class ="field">
                <%= f.text_area :response, rows: '5', placeholder:"返信はここへ記入" %>
              </div>
            </div>
            <div class ="action">
              <%= f.submit "送信する" ,class:"btn btn-block btn-info mt-3"%>
            </div>
            <% end %>
          </div>

<!--以下、responseに関するコード-->

          <div class ="col-md-8 mx-3">
           <table class ="table table-bordered">
            <thead>
              <tr>
                <th>返信者</th>
                <th>返信コメント</th>
              </tr>
            </thead>
            <tbody>
              <% @comment.responses.each do |response| %>
              <tr>
                <td>
                  <%= image_tag response.user.get_profile_image(100,100) %><br>
                  <%= response.user.name %><br>
                  <%= response.created_at.strftime('%Y/%m/%d') %>
                  <% if response.user == current_user %>
                    <%= link_to "削除する", comment_response_path(response.comment, response), method: :delete %>
                  <% end %>
                </td>
                <td>
                  <%= response.response %>
                </td>
              </tr>
              <% end %>
            </tbody>
           </table>
          </div>
          
        </div>
      </div>
    </div>
  </div>
</div>

app/views/favorites/index.html.erb
<div class ="container-fluid">
  <div class="row no-gutters">
    <div class="col-md-8 mx-5 mx-sm-auto text-center shadow-lg rounded px-0 my-4">
      <h3 class ="text-light bg-dark py-3 mb-0">いいね一覧</h3>

       <div class ="col-md-10 offset-md-1">
       <table class ="table table-hover">
        <thead>
         <tr>
          <th></th>
          <th>タイトル</th>
          <th>本文</th>
         </tr>
        </thead>
        <tbody>
          <% @favorites.each do |favorite| %>
          <tr>
          <td>
            <%= image_tag favorite.comment.user.get_profile_image(100,100) %>
            <%= link_to comment_path(favorite.comment.id) do%>
              <p><%= favorite.comment.user.name %></p>
            <% end %>
          </td>
          <td>
            <%= link_to comment_path(favorite.comment.id) do%>
             <%= favorite.comment.title %>
            <% end %>
          </td>
          <td>
            <%= favorite.comment.body %>
          </td>
          </tr>
         <% end %>

         </div>

        </tbody>
      </table>
      </div>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<div class="container-fluid">
  <div class="row no-gutters">
    <div class="col-md-6 mx-4 mx-sm-auto text-center shadow-lg rounded px-0 my-5">
      <h5 class="text-light bg-dark py-4 mb-0">当コミュニティサイトについて</h5>
       <div class="form-group p-4">

        <p>
          <strong>
          全国高齢者いきいきサロン　オンライン
          </strong>
          へようこそ
        </p><br>

        <p>遠くにいる方とも交流をしてみたい、</p>
        <p>感染症が気になりなかなか外出ができない、</p>
        <p>お身体やご家庭の事情で室内で過ごすことが多くなった。</p><br>

        <p>そんな方々がオンライン上で集えるスペースが誕生しました。</p><br>

        <p>まずは
        <%= link_to "ゲストログイン（お試し利用）", guest_sign_in_path, method: :post %>
        にて、みなさんの投稿を見てみましょう。</p>

      </div>
    </div>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container-fluid">
  <div class="row no-gutters">
    <div class="col-md-6 mx-2 mx-sm-auto text-center shadow-lg rounded px-0 my-5">
      <h3 class="text-light bg-dark py-4 mb-0">全国高齢者いきいきサロン　オンライン</h3>

      <div class="form-group p-4">
        <p><%= link_to "サイトに関して", about_path %></p>
        <p><%= link_to "ゲストログイン（お試し利用）", guest_sign_in_path, method: :post %></p>
        <p><%= link_to "新規登録", new_user_registration_path %></p>
        <p><%= link_to "ログイン", new_user_session_path %></p>
      </div>

    </div>
  </div>
</div>

app/views/searches/search.html.erb
<div class ="container-fluid">
  <div class="row no-gutters">
    <div class="col-md-8 mx-5 mx-sm-auto text-center shadow-lg rounded px-0 my-4">
      <h3 class ="text-light bg-dark py-3 mb-0">検索結果</h3>

        <div class="row">
          <div class ="col-md-9 mx-3">
  
           <table class ="table table-bordered">
              <thead>
               <tr>
                <th></th>
                <th>タイトル</th>
                <th>本文</th>
               </tr>
              </thead>

            <!--モデルがUserの時 -->
            <% if @range == "User" %>
              <tbody>
              <% @users.each do |user| %>
                <tr>
                  <td><%= user.name %></td>
                </tr>
              <% end %>
              </tbody>
             <% else %>
           
            <!--モデルがUserではない時(Commentの時) -->              
              <tbody>
                <% @comments.each do |comment| %>
                <tr>
                  <td>
                    <%= image_tag comment.user.get_profile_image(100,100) %><br>
                    <%= link_to user_path(comment.user) do %>
                    <%= comment.user.name %>
                    <% end %>
                  </td>
                  <td><%= comment.title %></td>
                  <td><%= comment.body %></td>
                </tr>
                 <% end %>
              </tbody>
            <% end %>
            
          </table>

      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="container-fluid">
  <div class="row no-gutters">
    <div class="col-md-3 mx-2 mx-sm-auto text-center shadow-lg rounded px-0 my-5">
      <h5 class="text-light bg-dark py-4 mb-0">プロフィール編集</h5>
      <div class="form-group p-2">

      <div>
        <% if @user.errors.any? %>
        <ul>
          <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
          <% end %>
        </ul>
        <% end %>
      </div>

      <div class ="mx-auto text-center">
        <% if @user.email == 'guest@example.com'%>
      <p>ゲストユーザーはユーザー情報の編集ができません。</p>
        <%= link_to "投稿一覧へ戻る", comments_path %>
        <% else %>

        <%= form_with model: @user do |f| %>
        <div class="form-group">
          <div class="field">
            <label>名前</label>
            <%= f.text_field :name, autofocus: true, id:"inputName" %>
          </div>
        </div>

        <div class="form-group">
          <div class="field">
            <label>プロフィール画像</label>
            <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %>
          </div>
        </div>


        <div class ="actions">
          <%= f.submit "変更を保存する", class:"btn btn-lg btn-block btn-info mt-3" %>
        </div>

        <% end %>

        <% end %>
      </div>

      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class ="container-fluid">
  <div class="row no-gutters">
    <div class="col-md-8 mx-5 mx-sm-auto text-center shadow-lg rounded px-0 my-4">
      <h3 class ="text-light bg-dark py-3 mb-0">マイページ</h3>

        <div class="row">
          <div class = "col-md-2 mx-5 mx-sm-auto">
                <%= image_tag @user.get_profile_image(100,100) %><br>
                <%= @user.name%><br><br>
                <% if @user == current_user %>
                  <p><%= link_to "プロフィールを編集する", edit_user_path %></p>
                <% end %>
                <%= link_to "いいね一覧", comment_favorites_path(comment_id: @comments.first.id) if @comments.present? %>
          </div>

          <div class ="col-md-9 mx-3">
           <table class ="table table-bordered">
            <thead>
              <tr>
                <th colspan ="2">投稿一覧</th>
              </tr>
            </thead>
            <tbody>
             <% @comments.each do |comment| %>
              <tr>
              <td class ="col-6 text-left">
                
                <!--投稿詳細に飛ぶようにしたい-->
                <p><%= comment.title %></p>
                
                
              </td>
              <td class ="col-6">
                <p><%= comment.body %></p>
                <%= link_to "#{comment.responses.count}件の返信", comment_path(comment.id) %>
                <% end %>
              </td>
              </tr>
            </div>
          </div>

        <%= paginate @comments %>

        </tbody>
      </table>
      </div>
    </div>
  </div>
</div>