config/routes.rb
Rails.application.routes.draw do
  root to: "homes#top"
  get "about" => "homes#about"
  devise_for :users
  resources :comments, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
    resource :favorite, only: [:create, :destroy]
    resources :favorites, only: [:index], param: :comment_id
    resources :responses, only: [:create, :destroy]
  end

  resources :users, only: [:show, :edit, :update]
  devise_scope :user do
    post 'users/guest_sign_in', to:'users/sessions#guest_sign_in', as: :guest_sign_in
  end
  get "search" => "searches#search"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/coment.rb
class Coment < ApplicationRecord
  
  has_one_attached :image
  belongs_to :user
  
end

app/models/comment.rb
class Comment < ApplicationRecord

  has_one_attached :image
  belongs_to :user
  has_many :responses, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
  
  def self.looks(search, word)
    if search == "perfect_match"
      @comment = Comment.where("body LIKE?", "#{word}")
    elsif search == "partial_match"
      @comment = Comment.where("body LIKE?", "%#{word}%")
    else
      @comment = Comment.all
    end
  end
  
  
end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :comment

  validates :user_id, uniqueness: {scope: :comment_id}

end

app/models/response.rb
class Response < ApplicationRecord

  belongs_to :user
  belongs_to :comment

  validates :response, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :comments, dependent: :destroy
  has_many :responses, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :name, presence: true, uniqueness: true

  has_one_attached :profile_image

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join("app/assets/images/no_image.jpg")
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.password_confirmation = user.password
      user.name = "ゲストユーザー"
    end
  end

  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?", "%#{word}%")
    else
      @user = User.all
    end
  end

 end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    comments_path
  end

  def after_sign_out_path_for(resource)
    about_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id
    if @comment.save
      flash[:notice] = "投稿に成功しました"
      redirect_to comments_path
    else
      flash.now[:notice] = "投稿に失敗しました"
      render :new
    end
  end

  def index
    @comments = Comment.page(params[:page])
  end

  def show
    @comment = Comment.find(params[:id])
    @response = Response.new
  end

  def destroy
    comment = Comment.find(params[:id])
    comment.destroy
    redirect_to comments_path
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])
    if @comment.update(comment_params)
      redirect_to comment_path(comment.id)
    else
      render :edit
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:title, :body)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    comment = Comment.find(params[:comment_id])
    favorite = current_user.favorites.new(comment_id: comment.id)
    favorite.save
    redirect_to comment_path(comment)
  end

  def destroy
    comment = Comment.find(params[:comment_id])
    favorite = current_user.favorites.find_by(comment_id: comment.id)
    favorite.destroy
    redirect_to comment_path(comment)
  end

  def index
    @comments = Comment.where(id: current_user.favorites.pluck(:comment_id))
    @favorites = current_user.favorites
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
before_action :authenticate_user!, except: [:top, :about]

  def top
  end

  def about
  end

end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController

  def create
    comment = Comment.find(params[:comment_id])
    response = current_user.responses.new(response_params)
    response.comment_id = comment.id
    if response.save
      flash[:notice] = "返信に成功しました"
      redirect_to comment_path(comment)
    else
      flash[:notice] = "返信に失敗しました"
      redirect_to comment_path(comment)
    end
  end

  def destroy
    Response.find(params[:id]).destroy
    redirect_to comment_path(params[:comment_id])
  end

  private

  def response_params
    params.require(:response).permit(:response)
  end

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :authenticate_user!
  
  def search
    @range = params[:range]
    
    if @range == "User"
      @users = User.looks(params[:search],params[:word])
    else
      @comments = Comment.looks(params[:search],params[:word])
    end
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @comments = @user.comments.page(params[:page])

  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id)
    else
      flash[:error] = "更新に失敗しました。"
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image)
  end

  def is_matching_login_user
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to comments_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coments_helper.rb
module ComentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/responses_helper.rb
module ResponsesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>iki-iki-online</title>
    <meta name="viewport" content="width=device-width,initial-scale=1, maximum-scale=1" >
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
      <div class = "header row px-3 py-4" style="background-color: #d8ffb6 ;">
        <div class = "col-2">
          <h5>rogo</h5>
        </div>

          <% if user_signed_in? %>
          <div class = "col-5 offset-5">
            <div class = "row">
              <div class = "col-3">
                <button type="button" class="btn btn-light border-dark">
                  <%= link_to "新規投稿", new_comment_path %>
                </button>
              </div>
              <div class = "col-3">
                <button type="button" class="btn btn-light border-dark">
                  <%= link_to "投稿一覧", comments_path %>
                </button>
              </div>
              <div class = "col-3">
                <button type="button" class="btn btn-light border-dark">
                  <%= link_to "マイページ", user_path(current_user.id) %>
                </button>
              </div>
              <div class = "col-3">
                <button type="button" class="btn btn-light border-dark">
                  <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
                </button>
              </div>
            </div>
            
            <!--検索機能-->
            <div class="search_form">
                <%= form_with url: search_path, local: true, method: :get do |f| %>
                  <%= f.text_field :word %>
                  <%= f.select :range, options_for_select([['名前'], ['本文']]) %>
                  <%= f.select :search, options_for_select([["完全一致","perfect_match"], ["部分一致","partial_match"]]) %>
                  <%= f.submit "検索", class: "btn btn-primary" %>
                <% end %>
            </div>
            
          </div>
          <% else %>
          <div class = "col-5 offset-5">
           <div class = "row">
              <div class = "col-3">
                <button type="button" class="btn btn-light border-dark">
                  <%= link_to "H O M E", root_path %>
                </button>
              </div>
              <div class = "col-3">
                <button type="button" class="btn btn-light border-dark">
                  <%= link_to "利用案内", about_path %>
                </button>
              </div>
              <div class = "col-3">
                <button type="button" class="btn btn-light border-dark">
                  <%= link_to "新規登録", new_user_registration_path %>
                </button>
              </div>
              <div class = "col-3">
                <button type="button" class="btn btn-light border-dark">
                  <%= link_to "ログイン", new_user_session_path %>
                </button>
              </div>
            </div>
          </div>
        <% end %>
        </div>
        </div>
      </nav>
    </header>

      <main>
        <div>
          <%= flash[:notice] %>
        </div>
      </main>
    <%= yield %>

    <footer>
      <div class = "container-fluid">
        <div class = "footer row" style="background-color: #d8ffb6 ;">
          <div class ="mx-auto">
            <p>PortFolio</p>
          </div>
        </div>
      </div>
    </footer>

  </body>
</html>